# product defaults
[Common]
chainlink_node_funding = 0.5

[NodeConfig]
BaseConfigTOML = """
[Feature]
FeedsManager = true
LogPoller = true
UICSAKeys = true

[Log]
Level = 'debug'
JSONConsole = true

[Log.File]
MaxSize = '0b'

[WebServer]
AllowOrigins = '*'
HTTPPort = 6688
SecureCookies = false
HTTPWriteTimeout = '1m'
SessionTimeout = '999h0m0s'

[WebServer.RateLimit]
Authenticated = 2000
Unauthenticated = 1000

[WebServer.TLS]
HTTPSPort = 0

[Database]
MaxIdleConns = 20
MaxOpenConns = 40
MigrateOnStartup = true

[OCR2]
Enabled = true

[Keeper]
TurnLookBack = 0

[Keeper.Registry]
PerformGasOverhead = 150000
SyncInterval = '5m0s'

[P2P]
[P2P.V2]
Enabled = true
ListenAddresses = ['0.0.0.0:6690']
AnnounceAddresses = ['0.0.0.0:6690']
DeltaDial = '500ms'
DeltaReconcile = '5s'
"""

[Keeper.Common]
registry_to_test = "2_1"
number_of_registries = 1
number_of_nodes = 6
number_of_upkeeps = 500
upkeep_gas_limit = 1500000
check_gas_to_burn = 100000
perform_gas_to_burn = 50000
max_perform_gas = 5000000
block_range = 3600
block_interval = 20
forces_single_tx_key = false
delete_jobs_on_end = true